export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAIL = 'GET_USER_LIST_FAIL';

export const GET_ESTUDENT_LIST_SUCCESS = 'GET_ESTUDENT_LIST_SUCCESS';
export const GET_ESTUDENT_LIST_FAIL = 'GET_ESTUDENT_LIST_FAIL';

export const GET_DOCENTE_LIST_SUCCESS = 'GET_DOCENTE_LIST_SUCCESS';
export const GET_DOCENTE_LIST_FAIL = 'GET_DOCENTE_LIST_FAIL';

export const GET_PERSONAL_LIST_SUCCESS = 'GET_PERSONAL_LIST_SUCCESS';
export const GET_PERSONAL_LIST_FAIL = 'GET_PERSONAL_LIST_FAIL';
