export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAIL = 'GET_USER_LIST_FAIL';

export const GET_ESTUDENT_LIST_SUCCESS = 'GET_ESTUDENT_LIST_SUCCESS';
export const GET_ESTUDENT_LIST_FAIL = 'GET_ESTUDENT_LIST_FAIL';

export const GET_DOCENTE_LIST_SUCCESS = 'GET_DOCENTE_LIST_SUCCESS';
export const GET_DOCENTE_LIST_FAIL = 'GET_DOCENTE_LIST_FAIL';

export const GET_PERSONAL_LIST_SUCCESS = 'GET_PERSONAL_LIST_SUCCESS';
export const GET_PERSONAL_LIST_FAIL = 'GET_PERSONAL_LIST_FAIL';

export const DELETE_ESTUDENT_SUCCESS = 'DELETE_ESTUDENT_SUCCESS';
export const DELETE_ESTUDENT_FAIL = 'DELETE_ESTUDENT_FAIL';

export const DELETE_DOCENTE_SUCCESS = 'DELETE_DOCENTE_SUCCESS';
export const DELETE_DOCENTE_FAIL = 'DELETE_DOCENTE_FAIL';

export const DELETE_PERSONAL_SUCCESS = 'DELETE_PERSONAL_SUCCESS';
export const DELETE_PERSONAL_FAIL = 'DELETE_PERSONAL_FAIL';
